# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-14 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Skill',
        ),
    ]
